# Generated by Django 5.0.4 on 2024-04-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.salesperson'),
        ),
        migrations.AddField(
            model_name='store',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.client'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.store'),
        ),
    ]
