# Generated by Django 5.0.4 on 2024-04-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_initial'),
        ('vendor_app', '0002_delete_admin_delete_supervisor_admin_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor_app.client'),
        ),
    ]
