# Generated by Django 5.0.4 on 2024-04-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_alter_store_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='client',
        ),
    ]
