# Generated by Django 5.0.4 on 2024-04-14 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_rename_contact_details_store_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesperson', to='client_app.salesperson'),
        ),
    ]
