# Generated by Django 5.0.4 on 2024-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
