# Generated by Django 5.0.4 on 2024-04-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_basecustomuser_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecustomuser',
            name='is_superadmin',
        ),
        migrations.AlterField(
            model_name='basecustomuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
