# Generated by Django 5.0.4 on 2024-04-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_remove_admin_client_remove_salesperson_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecustomuser',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='vendor_app.client'),
        ),
    ]
