# Generated by Django 5.0.4 on 2024-04-13 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_alter_basecustomuser_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecustomuser',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 4, 13, 22, 1, 12, 79380, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
